// ts-events.js — Placeholder event data + cover art generator
(function(global){
  // Curated palette mixes — used for procedural cover art (no external imgs)
  const COVERS = {
    nebula:   { a:'#7B3FE4', b:'#FF3FA4', c:'#1A0F33', accent:'#FFD0F0', kind:'gradient' },
    inferno:  { a:'#FF5E3A', b:'#8B1E3F', c:'#1B0708', accent:'#FFE0A0', kind:'gradient' },
    aqua:     { a:'#1FB6FF', b:'#7B3FE4', c:'#0A1430', accent:'#B0F0FF', kind:'gradient' },
    citrus:   { a:'#FFC847', b:'#FF6B3D', c:'#2A1505', accent:'#FFF1B5', kind:'gradient' },
    forest:   { a:'#27D17C', b:'#0F8FA1', c:'#03251E', accent:'#C5F8DD', kind:'gradient' },
    rose:     { a:'#FFB1C8', b:'#9B2D5E', c:'#270914', accent:'#FFE0EC', kind:'gradient' },
    midnight: { a:'#3F3FE4', b:'#1A0F33', c:'#06061A', accent:'#9090FF', kind:'gradient' },
    sunset:   { a:'#FF8847', b:'#D63384', c:'#2A0B22', accent:'#FFD08A', kind:'gradient' },
    mono:     { a:'#E0DCD3', b:'#8A8780', c:'#16140F', accent:'#FFFFFF', kind:'gradient' },
    electric: { a:'#A0FF1F', b:'#1FFFC8', c:'#0A220A', accent:'#FFFFFF', kind:'gradient' },
  };

  const EVENTS = [
    {
      id: 'arca-niteglow',
      title: 'ARCA',
      subtitle: 'KICK Live · Niteglow Tour',
      artist: 'Arca',
      category: 'Electronic',
      day: 'FRI', date: 14, month: 'JUN', time: '23:00',
      venue: 'Foro Sol',
      city: 'CDMX, MX',
      priceFrom: 65, priceTo: 220, currency: 'USD',
      tags: ['Avant-pop','Industrial','Late night'],
      availability: 'Selling fast',
      cover: 'nebula',
      hero: true,
      vibe: 'Hyper-electronic ceremony in 4D sound.',
    },
    {
      id: 'mitski-laurel',
      title: 'MITSKI',
      subtitle: 'The Land Is Inhospitable Tour',
      artist: 'Mitski',
      category: 'Indie',
      day: 'SAT', date: 22, month: 'JUN', time: '20:30',
      venue: 'Greek Theatre',
      city: 'Berkeley, CA',
      priceFrom: 58, priceTo: 145, currency: 'USD',
      tags: ['Indie','Singer-songwriter','Outdoor'],
      availability: 'Few left',
      cover: 'rose',
      hero: true,
      vibe: 'A choir of strings under June stars.',
    },
    {
      id: 'fkj-blue-room',
      title: 'FKJ',
      subtitle: 'V I N C E N T  Tour',
      artist: 'FKJ',
      category: 'Live',
      day: 'THU', date: 27, month: 'JUN', time: '21:00',
      venue: 'Blue Room',
      city: 'Buenos Aires, AR',
      priceFrom: 42, priceTo: 110, currency: 'USD',
      tags: ['Live looping','Jazz','Lounge'],
      availability: 'On sale',
      cover: 'aqua',
      hero: true,
      vibe: 'One man, twelve instruments, infinite loops.',
    },
    {
      id: 'cobra-clubnight',
      title: 'COBRA',
      subtitle: 'Club Night · Resident Series',
      artist: 'Cobra & friends',
      category: 'Electronic',
      day: 'SAT', date: 06, month: 'JUL', time: '00:00',
      venue: 'Club Cobra',
      city: 'Berlín, DE',
      priceFrom: 28, priceTo: 35, currency: 'USD',
      tags: ['Techno','All night','18+'],
      availability: 'On sale',
      cover: 'electric',
    },
    {
      id: 'hamilton',
      title: 'HAMILTON',
      subtitle: 'An American Musical',
      artist: 'Cast Latinoamérica',
      category: 'Theatre',
      day: 'SUN', date: 13, month: 'JUL', time: '19:00',
      venue: 'Teatro Colón',
      city: 'Buenos Aires, AR',
      priceFrom: 75, priceTo: 320, currency: 'USD',
      tags: ['Musical','Family','Spanish'],
      availability: 'Selling fast',
      cover: 'citrus',
    },
    {
      id: 'rhcp-stadium',
      title: 'RED HOT CHILI PEPPERS',
      subtitle: 'Unlimited Love World Tour',
      artist: 'Red Hot Chili Peppers',
      category: 'Rock',
      day: 'WED', date: 17, month: 'JUL', time: '20:00',
      venue: 'Estadio Único',
      city: 'La Plata, AR',
      priceFrom: 95, priceTo: 480, currency: 'USD',
      tags: ['Rock','Stadium','Classic'],
      availability: 'On sale',
      cover: 'inferno',
    },
    {
      id: 'sofi-tukker',
      title: 'SOFI TUKKER',
      subtitle: 'BREAD TOUR',
      artist: 'Sofi Tukker',
      category: 'Electronic',
      day: 'FRI', date: 25, month: 'JUL', time: '22:00',
      venue: 'Movistar Arena',
      city: 'CDMX, MX',
      priceFrom: 52, priceTo: 180, currency: 'USD',
      tags: ['Dance','House','Bilingual'],
      availability: 'On sale',
      cover: 'sunset',
    },
    {
      id: 'phoebe',
      title: 'PHOEBE BRIDGERS',
      subtitle: 'Punisher Anniversary Tour',
      artist: 'Phoebe Bridgers',
      category: 'Indie',
      day: 'SAT', date: 02, month: 'AUG', time: '20:00',
      venue: 'Ford Theatre',
      city: 'Hollywood, CA',
      priceFrom: 68, priceTo: 195, currency: 'USD',
      tags: ['Indie','Skeleton suit','Outdoor'],
      availability: 'Few left',
      cover: 'midnight',
    },
    {
      id: 'kraftwerk',
      title: 'KRAFTWERK 3-D',
      subtitle: 'The Catalogue · 50th Anniversary',
      artist: 'Kraftwerk',
      category: 'Electronic',
      day: 'TUE', date: 12, month: 'AUG', time: '21:00',
      venue: 'Auditorio Nacional',
      city: 'CDMX, MX',
      priceFrom: 85, priceTo: 260, currency: 'USD',
      tags: ['Electronic','3D','Legacy'],
      availability: 'Selling fast',
      cover: 'forest',
    },
    {
      id: 'comedy-night',
      title: 'STAND-UP NIGHT',
      subtitle: 'Resident comics & guest sets',
      artist: 'Varios',
      category: 'Comedy',
      day: 'THU', date: 14, month: 'AUG', time: '21:30',
      venue: 'Niceto Club',
      city: 'Buenos Aires, AR',
      priceFrom: 22, priceTo: 38, currency: 'USD',
      tags: ['Comedy','Local','Spanish'],
      availability: 'On sale',
      cover: 'mono',
    },
  ];

  global.TS_EVENTS = EVENTS;
  global.TS_COVERS = COVERS;
})(window);
